<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260611175556 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE enseignant (specialite VARCHAR(100) NOT NULL, id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE etudiant (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(100) NOT NULL, prenom VARCHAR(100) NOT NULL, email VARCHAR(180) NOT NULL, filiere VARCHAR(100) NOT NULL, theme_memoire VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_717E22E3E7927C74 ON etudiant (email)');
        $this->addSql('CREATE TABLE salle (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(50) NOT NULL, capacite INT NOT NULL, localisation VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE soutenance (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date DATE NOT NULL, heure TIME(0) WITHOUT TIME ZONE NOT NULL, etudiant_id INT NOT NULL, salle_id INT NOT NULL, president_id INT NOT NULL, rapporteur_id INT NOT NULL, examinateur_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_4D59FF6EDC304035 ON soutenance (salle_id)');
        $this->addSql('CREATE INDEX IDX_4D59FF6EB40A33C7 ON soutenance (president_id)');
        $this->addSql('CREATE INDEX IDX_4D59FF6E2AF5D182 ON soutenance (rapporteur_id)');
        $this->addSql('CREATE INDEX IDX_4D59FF6E9D8D68C0 ON soutenance (examinateur_id)');
        $this->addSql('CREATE UNIQUE INDEX unique_etudiant ON soutenance (etudiant_id)');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(100) NOT NULL, prenom VARCHAR(100) NOT NULL, email VARCHAR(180) NOT NULL, password VARCHAR(255) NOT NULL, roles JSON NOT NULL, discr VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D93D649E7927C74 ON "user" (email)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE enseignant ADD CONSTRAINT FK_81A72FA1BF396750 FOREIGN KEY (id) REFERENCES "user" (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE soutenance ADD CONSTRAINT FK_4D59FF6EDDEAB1A3 FOREIGN KEY (etudiant_id) REFERENCES etudiant (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE soutenance ADD CONSTRAINT FK_4D59FF6EDC304035 FOREIGN KEY (salle_id) REFERENCES salle (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE soutenance ADD CONSTRAINT FK_4D59FF6EB40A33C7 FOREIGN KEY (president_id) REFERENCES enseignant (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE soutenance ADD CONSTRAINT FK_4D59FF6E2AF5D182 FOREIGN KEY (rapporteur_id) REFERENCES enseignant (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE soutenance ADD CONSTRAINT FK_4D59FF6E9D8D68C0 FOREIGN KEY (examinateur_id) REFERENCES enseignant (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE enseignant DROP CONSTRAINT FK_81A72FA1BF396750');
        $this->addSql('ALTER TABLE soutenance DROP CONSTRAINT FK_4D59FF6EDDEAB1A3');
        $this->addSql('ALTER TABLE soutenance DROP CONSTRAINT FK_4D59FF6EDC304035');
        $this->addSql('ALTER TABLE soutenance DROP CONSTRAINT FK_4D59FF6EB40A33C7');
        $this->addSql('ALTER TABLE soutenance DROP CONSTRAINT FK_4D59FF6E2AF5D182');
        $this->addSql('ALTER TABLE soutenance DROP CONSTRAINT FK_4D59FF6E9D8D68C0');
        $this->addSql('DROP TABLE enseignant');
        $this->addSql('DROP TABLE etudiant');
        $this->addSql('DROP TABLE salle');
        $this->addSql('DROP TABLE soutenance');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
